# PyInstaller spec for Malamjaba Backend
# Run with: pyinstaller backend.spec

import os
import sys
from pathlib import Path

# Get the backend directory - spec file is in backend dir
backend_dir = Path.cwd()

# Data files to include
datas = [
    (str(backend_dir / "alembic"), "alembic"),
    (str(backend_dir / "alembic.ini"), "."),
    (str(backend_dir / "app" / "templates"), "app/templates"),
]

# Hidden imports for SQLAlchemy, FastAPI, etc.
hiddenimports = [
    "uvicorn",
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.lifespan.on",
    "sqlalchemy",
    "sqlalchemy.dialects.sqlite",
    "sqlalchemy.dialects.postgresql",
    "asyncpg",
    "aiosqlite",
    "pydantic",
    "pydantic_settings",
    "passlib",
    "passlib.handlers.bcrypt",
    "bcrypt",
    "jose",
    "jose.backends",
    "python_multipart",
    "jinja2",
    "openpyxl",
    "aiofiles",
    "dateutil",
    "dateutil.parser",
    "dateutil.tz",
    "psycopg2",
    "alembic",
    "alembic.config",
    "alembic.script",
    "alembic.environment",
    "alembic.migration",
    "app",
    "app.main",
    "app.config",
    "app.database",
    "app.core.exceptions",
    "app.core.permissions",
    "app.core.validators",
    "app.api.router",
    "app.api.auth",
    "app.api.users",
    "app.api.agents",
    "app.api.candidates",
    "app.api.medical_tokens",
    "app.api.visas",
    "app.api.tickets",
    "app.api.payments",
    "app.api.expenses",
    "app.api.dashboard",
    "app.api.ledger",
    "app.api.notifications",
    "app.api.settings",
    "app.api.reports",
    "app.api.documents",
    "app.api.vendors",
    "app.models.user",
    "app.models.agent",
    "app.models.candidate",
    "app.models.visa",
    "app.models.ticket",
    "app.models.payment",
    "app.models.expense",
    "app.models.medical_token",
    "app.models.ledger",
    "app.models.document",
    "app.models.notification",
    "app.models.settings",
    "app.models.audit_log",
    "app.models.backup_log",
    "app.models.vendor",
    "app.schemas.common",
    "app.schemas.user",
    "app.schemas.agent",
    "app.schemas.candidate",
    "app.schemas.visa",
    "app.schemas.ticket",
    "app.schemas.payment",
    "app.schemas.expense",
    "app.schemas.medical_token",
    "app.schemas.ledger",
    "app.schemas.document",
    "app.schemas.notification",
    "app.schemas.settings",
    "app.schemas.report",
    "app.schemas.backup",
    "app.schemas.audit_log",
    "app.schemas.vendor",
    "app.services.auth_service",
    "app.services.number_generator",
    "app.services.pdf_service",
    "app.seeds.seed_data",
]

# Create spec
a = Analysis(
    ["run_production.py"],
    pathex=[str(backend_dir)],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        "tkinter", "matplotlib", "numpy", "pandas", "scipy",
        "pytest", "pytest_asyncio", "httpx",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=None,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=None)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="malamjaba-backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)